import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [nome, setNome] = useState("");
  const [idade, setIdade] = useState("");
  const [cidade, setCidade] = useState("");
  const [nova, setNova] = useState(false);
  const [itens, setItens] = useState([
    {
      id: 0,
      nome: "Gustavo",
      idade: 18,
      cidade: "SP",
    },
  ]);

  const generateGuid = () => {
    var result, i, j;
    result = "";
    for (j = 0; j < 32; j++) {
      if (j == 8 || j == 12 || j == 16 || j == 20) result = result + "-";
      i = Math.floor(Math.random() * 16)
        .toString(16)
        .toUpperCase();
      result = result + i;
    }
    return result;
  };

  const salvar = () => {
    if(nome.trim() !== "" && idade.trim() !== "" && cidade.trim() !== ""){ 
      setItens([
        ...itens,
        {
          id: generateGuid(),
          nome: nome,
          idade: idade,
          cidade: cidade,
        },
      ]);
      setNome("");
      setIdade("");
      setCidade("");
      setNova(false);
    }else{
      alert("Preencha todos os campos!")
    }
  };

  const excluir = (id) => {
    console.log(
      id,
      itens.filter((i) => i.id != id)
    );

    setItens(itens.filter((i) => i.id != id));
  };
  const editar = (id) => {
    const item = itens.find((i) => i.id == id);
    excluir(id);
    setNova(true);
    setNome(item.nome);
    setIdade(item.idade);
    setCidade(item.cidade);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header">
        <h3>Gustavo Gomes Macario</h3>
      </header>
      <div className="container">
        <table id="pTabela" cellspacing="0">
          <thead>
            <th style={{ width: 200 }}>Nome</th>
            <th style={{ width: 150 }}>Idade</th>
            <th style={{ width: 150 }}>Cidade</th>
            <th style={{ width: 100 }}></th>
          </thead>
          <tbody id="table-content">
            {itens.map((item) => (
              <tr key={item.id}>
                <td>
                  <span>{item.nome}</span>
                </td>
                <td>
                  <span>{item.idade}</span>
                </td>
                <td>
                  <span>{item.cidade}</span>
                </td>
                <td>
                  <button className="delete-button" onClick={() => excluir(item.id)}>Excluir</button>
                  <button className="edit-button" onClick={() => editar(item.id)}>Alterar</button>
                </td>
              </tr>
            ))}
            {nova && (
              <tr>
                <td>
                  <input
                    type="text"
                    name=""
                    id=""
                    value={nome}
                    onChange={(e) => setNome(e.target.value)}
                  />
                </td>
                <td>
                  <input
                    maxLength={3}
                    type="number"
                    name=""
                    id=""
                    value={idade}
                    onChange={(e) => setIdade(e.target.value)}
                  />
                </td>
                <td>
                  <input
                    maxLength={2}
                    type="text"
                    name=""
                    id=""
                    value={cidade}
                    onChange={(e) => setCidade(e.target.value)}
                  />
                </td>

                <td>
                  <button className="save-button" onClick={() => salvar()}>Salvar</button>
                </td>
              </tr>
            )}
          </tbody>
        </table>
        <div className="button-box">
          <button onClick={() => setNova(true)}>Adicionar Linha</button>
        </div>
      </div>
    </div>
  );
}
